Repository 1917090/textutils, pull requests merged in 2022-10, with the labels that each got.

#1 Update App.js
  src/App.js
Labels: good first issue, hacktoberfest-accepted

#2 Delete login.jsx
  src/componets/login.jsx
Labels: enhancement, good first issue, hacktoberfest-accepted

#4 Update App.js
  src/App.js
Labels: enhancement, hacktoberfest-accepted

#3 Update index.css
  src/index.css
Labels: good first issue, hacktoberfest-accepted
